### ISSUE TITLE
❌ Can't install 

### ISSUE THREAD

**Issue by MasterCruelty** [archetipico/DeCipher#1]
When I try to execute <code>install.sh</code> on my raspberry pi I receive this output.
![image](https://user-images.githubusercontent.com/72561502/130328430-51e9d938-aa05-4cf1-b003-bb807bb2885c.png)

**Comment by archetipico** [comment]
Fixed at [commit](https://github.com/archetipico/DeCipher/commit/c7af9c101803ede4517bd3e674a59c97a7fe3c13)
